cargo-features = ["profile-rustflags"]

[package]
name = "sto"
version = "0.1.0"
edition = "2021"

[dependencies]
pretty_env_logger = "0.4.0"
log = "0.4.17"
deadqueue = "0.2.4"
cached = "0.40"
highway = "0.8"
serde = "1.0"
rmp-serde = "1.1"
dashmap = "5.4"
anyhow = "1.0"
regex = "1.7.0"
lazy_static = "1.4.0"
#rusqlite = { version = "0.28.0", features = ["bundled"] }
tokio = { version = "1.22.0", features = ["full"] }
#tokio-rusqlite = "0.3.0"
#bincode = "1.3.3"
once_cell = "1.16.0"
serde_derive = "1.0.147"
clap = { version = "4.0.26", features = ["derive"] }
tera = "1.17.1"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
rustflags = ["-Ctarget-cpu=native"]
#, "-Z tune-cpu=machine"]

