cargo-features = ["profile-rustflags"]

[package]
name = "sto"
version = "0.1.0"
edition = "2021"

[dependencies]
test-log = "0.2"
env_logger = "0.9"
tracing = "0.1"
tracing-subscriber = "0.2"
deadqueue = "0.2.4"
cached = "0.40"
highway = "0.8"
ahash = "0.8"
clap = "4.0"
serde = "1.0"
rmp-serde = "1.1"
dashmap = "5.4"
anyhow = "1.0"
regex = "1.7.0"
lazy_static = "1.4.0"
rusqlite = { version = "0.28.0", features = ["bundled"] }
tokio = { version = "1.22.0", features = ["full"] }
tokio-rusqlite = "0.3.0"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
rustflags = ["-Ctarget-cpu=native", "-Z tune-cpu=machine"]

