cargo-features = ["profile-rustflags"]

[package]
name = "sto"
version = "0.1.0"
edition = "2021"

[dependencies]
test-log = "0.2"
env_logger = "0.9"
tracing = "0.1"
tracing-subscriber = "0.2"
cached = "0.40"
#linux-perf-event-reader = "0.8"
highway = "0.8"
ahash = "0.8"
clap = "4.0"
rayon = "1.5"
serde = "1.0"
rmp-serde = "1.1"
dashmap = "5.4"
#blazesym = "0.1"
anyhow = "1.0"
thiserror = "1.0"
binrw = "0.10"
[dev-dependencies]
test-log = "0.2"
file_diff = "1.0.0"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
rustflags = ["-Ctarget-cpu=native", "-Z tune-cpu=machine"]

[patch.crates-io]
binrw = { git = 'https://github.com/csnover/binrw' }

